apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sravas

resources:
  - namespace.yaml
  - ingress-class.yaml
  - ingress.yaml
  - mongodb/
  - elasticsearch/
  - kafka/
  - services/
  - hpa/
