apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  labels:
    app: scheduler-service
spec:
  type: ClusterIP
  selector:
    app: scheduler-service
  ports:
    - port: 3009
      name: http
