apiVersion: v2
name: sravas
description: Sravas - YouTube Clone
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  # Go services
  - name: api-gateway
    version: 0.1.0
    repository: file://charts/api-gateway
  - name: auth-service
    version: 0.1.0
    repository: file://charts/auth-service
  - name: user-service
    version: 0.1.0
    repository: file://charts/user-service
  - name: upload-service
    version: 0.1.0
    repository: file://charts/upload-service
  - name: streaming-service
    version: 0.1.0
    repository: file://charts/streaming-service
  - name: search-service
    version: 0.1.0
    repository: file://charts/search-service
  - name: comment-service
    version: 0.1.0
    repository: file://charts/comment-service
  - name: analytics-service
    version: 0.1.0
    repository: file://charts/analytics-service
  - name: notification-service
    version: 0.1.0
    repository: file://charts/notification-service
  - name: scheduler-service
    version: 0.1.0
    repository: file://charts/scheduler-service
  # Frontend
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend
  # Infrastructure
  - name: mongodb
    version: 0.1.0
    repository: file://charts/mongodb
  - name: elasticsearch
    version: 0.1.0
    repository: file://charts/elasticsearch
  - name: kafka
    version: 0.1.0
    repository: file://charts/kafka
